# Generated by Django 4.0.1 on 2022-07-31 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(choices=[('Bogotá', 'Bogotá'), ('Armenia', 'Armenia'), ('Barranquilla', 'Barranquilla'), ('Bucaramanga', 'Bucaramanga'), ('Cali', 'Cali'), ('Cartagena', 'Cartagena'), ('Cucuta', 'Cucuta'), ('Ibague', 'Ibague'), ('Manizales', 'Manizales'), ('Medellin', 'Medellin'), ('Pereira', 'Pereira'), ('Santa Marta', 'Santa Marta'), ('Villavicencio', 'Villavicencio')], default='Bogotá', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudad',
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='Habitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.PositiveBigIntegerField(unique=True)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.PositiveBigIntegerField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_id', to='app.ciudad')),
            ],
            options={
                'verbose_name': 'Habitante',
                'verbose_name_plural': 'Habitantes',
                'db_table': 'habitantes',
            },
        ),
    ]
